@startuml tp
class Admin {

    + addCategory(category: Category): void
    + addHousingType(housing: HousingType): void
    + addService(service: Service): void
    + getServices(): List<Service>
    + addHousing(housing: Housing): void
    + getTopTenTenants(): List<Tenant>
    + getFreeHousings(): Set<Housing>
    + occupationRate(): double
    - busyHousings(): Set<Housing>
}

Admin -->"1" Categories :categories
Admin -->"1" HousingTypes :housingTypes
Admin -->"1" Services :services
Admin -->"1" BookingSystem :bookingSystem
Admin -->"*" Housing :housings

class BookingSystem implements BookingAcceptedObserver{

    +notifyBookingAccepted(booking:Booking) : void
    +processBooking( booking:Booking) : void
    -isHousingAvailable( booking:Booking) : boolean
    +cancelBooking( booking:Booking) : void
    -notifyObserversBookingAccepted( booking:Booking) : void
    +getAllBookings( tenant:Tenant) : List<Booking>
    +getAllBookings() : List<Booking>
    +getFutureBookings( tenant:Tenant) : List<Booking>
    +getBookingsFromCity( tenant:Tenant,  city:City) : List<Booking>
    +getBookingCities( tenant:Tenant) :  List<City>
}

BookingSystem  -->"*"  Booking : confirmedBookings
BookingSystem  -->"*"  Booking : conditionalBookings
BookingSystem  -->"*"  BookingCancelledObserver : bookingCancelledObservers
BookingSystem  -->"*"  Housing : conditionalBookings
BookingSystem  -->"*"  BookingAcceptedObserver : bookingAcceptedObservers

class Address {
    - houseLocation: String

    + getHouseLocation(): String
    + getCity(): City
    + getCountry(): Country
}
Address -->"1" Country:country
Address -->"1" City:city

class Booking implements BookingAcceptanceObservable{

    + Booking(housing: Housing, tenant: Tenant, range: DateRange, paymentMethod: PaymentMethod)
    + getTenant(): Tenant
    + getHousing(): Housing
    + getOwner(): Owner
    + getRange(): DateRange
    + addObserver(observer: BookingAcceptedObserver): void
    + removeObserver(observer: BookingAcceptedObserver): void
    + checkOut(rankings: List<Ranking>): void
    + startsAfter(date: LocalDate): boolean
    + isOnCity(city: City): boolean
    + getCity(): City
    + isBookedOn(date: LocalDate): boolean
    + cancelBook(): void
    + acceptBook(): void
}

Booking -->"1" Housing : housing
Booking -->"1" Tenant : tenant
Booking -->"1" DateRange : range
Booking -->"1" PaymentMethod : paymentMethod
Booking -->"*" BookingAcceptedObserver : bookingObservers

abstract class CancellationPolicy {

    + CancellationPolicy(housing: Housing)
    + getHousing(): Housing
    + getCancellationFee(range: DateRange): double
}

CancellationPolicy -->"1" Housing : housing

class Category {
    - name: String

    + Category(name: String)
    + getName(): String
}

class CategoryScore {
    - score: int

    + CategoryScore(category: Category, score: int)
    + getCategory(): Category
    + getScore(): int
}

CategoryScore -->"1" Category : category

class City {
    - name: String

    + City(name: String)
    + getName(): String
}

class Country {
    - name: String

    + Country(name: String)
    + getName(): String
}

class DateRange {
    - start: LocalDate
    - end: LocalDate

    + DateRange(start: LocalDate, end: LocalDate)
    + getStart(): LocalDate
    + getEnd(): LocalDate
    + getOverlapDays(other: DateRange): long
    + overlaps(other: DateRange): boolean
    + startsAfter(date: LocalDate): boolean
    + contains(date: LocalDate): boolean
}


class Housing implements Rankeable {
    - area: float
    - capacity: int

    + Housing(housingType: HousingType, area: float, address: Address, services: List<Service>, 
              capacity: int, pictures: List<Picture>, stayDetails: HousingStayDetails, 
              paymentMethods: List<PaymentMethod>, priceCalculator: PriceCalculatorInterface, 
              owner: Owner, cancellationPolicy: CancellationPolicy)
    + getPrice(range: DateRange): double
    + getCapacity(): int
    + getAddress(): Address
    + isLocatedIn(city: City): boolean
    + isAvailable(dateRange: DateRange): boolean
    + getOwner(): Owner
    + getRankings(): List<Ranking>
    + addRanking(ranking: Ranking): void
    + getCity(): City
    + getCancelationFee(range: DateRange): double
    + getDefaultPaymentMethod(): PaymentMethod
}

Housing -->"1" HousingType : housingType
Housing -->"1" Address : address
Housing -->"*" Service : services
Housing -->"*" Picture : pictures
Housing -->"1" HousingStayDetails : stayDetails
Housing -->"*" PaymentMethod : paymentMethods
Housing -->"1" PaymentMethod : defaultPaymentMethod
Housing -->"1" PriceCalculatorInterface : priceCalculator
Housing -->"*" Ranking : rankings
Housing -->"1" Owner : owner
Housing -->"1" CancellationPolicy : cancellationPolicy

class HousingStayDetails {
    - checkIn: LocalDateTime
    - checkOut: LocalDateTime

    + HousingStayDetails(checkIn: LocalDateTime, checkOut: LocalDateTime)
    + getCheckIn(): LocalDateTime
    + getCheckOut(): LocalDateTime
}

class HousingType {
    - name: String

    + HousingType(name: String)
    + getName(): String
}

class Owner extends User implements Rankeable, Ranker{

    + Owner(fullName: String, email: String, phoneNumber: String, createdOn: LocalDateTime, bookingAcceptanceStrategy: BookingAcceptanceStrategy)
    + addRental(rental: Booking): void
    + getRentals(): List<Booking>
    + addRanking(ranking: Ranking): void
    + getRankings(): List<Ranking>
    + rank(ranking: Ranking): void
    + accept(booking: Booking): void
    + cancelBook(booking: Booking): void
}

Owner -->"*" Ranking:rankings
Owner -->"*" Booking:rentals
Owner -->"1" BookingAcceptanceStrategy:bookingAcceptanceStrategy

class Picture {
    - name: String
    - resourceUrl: String

    + Picture(name: String, resourceUrl: String)
    + getName(): String
    + getResourceUrl(): String
}

class PriceForRange {
    - price: double

    + PriceForRange(price: double, range: DateRange)
    + getPriceForRange(range: DateRange): double
}

PriceForRange -->"1" DateRange: range

class Ranking {
    - comment: String
    - rankedOn: LocalDate

    + Ranking(ranker: Ranker, ranked: Rankeable, comment: String, categoryScores: List<CategoryScore>)
    + getScores(): List<CategoryScore>
    + getComment(): String
    + getRanker(): Ranker
    + getRanked(): Rankeable
    + getRankedOn(): LocalDate
}

Ranking -->"1" Ranker:ranker
Ranking -->"1" Rankeable:ranked
Ranking -->"*" CategoryScore:categoryScores

class Tenant extends User implements Rankeable, Ranker{

    + Tenant(fullName: String, email: String, phoneNumber: String, createdOn: LocalDateTime)
    + addRanking(ranking: Ranking): void
    + getRankings(): List<Ranking>
    + rank(ranking: Ranking): void
    + book(housing: Housing, range: DateRange, paymentMethod: PaymentMethod, observers: List<BookingAcceptedObserver>): void
}

Tenant -->"*" Ranking:rankings

class User {
    - fullName: String
    - email: String
    - phoneNumber: String
    - createdOn: LocalDateTime

    + User(fullName: String, email: String, phoneNumber: String, createdOn: LocalDateTime)
    + getFullName(): String
    + getEmail(): String
    + getPhoneNumber(): String
    + getCreatedOn(): LocalDateTime
}

class BookingConditionalStrategy implements BookingStrategy{

    + BookingConditionalStrategy(conditionalBookings: Map<Housing, Queue<Booking>>)
    + process(booking: Booking): void
}

BookingConditionalStrategy -->"*" Booking :conditionalBookings
BookingConditionalStrategy -->"*" Housing :conditionalBookings

class BookingConfirmedStrategy implements BookingStrategy{

    + BookingConfirmedStrategy(confirmedBookings: Set<Booking>)
    + process(booking: Booking): void
}

confirmedBookings -->"*" Booking: confirmedBookings

class CancellationEmailSender implements BookingCancelledObserver{

    + CancellationEmailSender(emailSender: EmailSender)
    + notifyBookingCancelled(booking: Booking): void
}

CancellationEmailSender -->"1" EmailSender:emailSender

class Cash  implements PaymentMethod{
    + applyCharge(amount: double): void
    + receivePayment(amount: double): void
}

class ConfirmationEmailSender  implements BookingAcceptedObserver{
    + notifyBookingAccepted(booking: Booking): void
}

ConfirmationEmailSender -->"1" EmailSender:emailSender

class CreditCard implements PaymentMethod{
    + applyCharge(amount: double): void
    + receivePayment(amount: double): void
}

class DebitCard implements PaymentMethod {
    + applyCharge(amount: double): void
    + receivePayment(amount: double): void
}

class EventPublisherImpl implements EventPublisher{

    + subscribeToPriceDrop(subscriber: PriceDropSubscriber): void
    + unsubscribeFromPriceDrop(subscriber: PriceDropSubscriber): void
    + subscribeToReservationCancelled(subscriber: ReservationCancelledSubscriber): void
    + unsubscribeFromReservationCancelled(subscriber: ReservationCancelledSubscriber): void
    + subscribeToReservationAccepted(subscriber: ReservationAcceptedSubscriber): void
    + unsubscribeFromReservationAccepted(subscriber: ReservationAcceptedSubscriber): void
    + notifyPriceDrop(propertyType: String, newPrice: double): void
    + notifyReservationCancelled(propertyType: String): void
    + notifyReservationAccepted(booking: Booking): void
}

EventPublisherImpl -->"*" PriceDropSubscriber:priceDropSubscribers
EventPublisherImpl -->"*" ReservationCancelledSubscriber:reservationCancelledSubscribers
EventPublisherImpl -->"*" ReservationAcceptedSubscriber:reservationAcceptedSubscribers

class FreeCancellation extends CancellationPolicy{
    - MAX_DAYS_FOR_FREE_CANCELLATION: int

    + getCancellationFee(range: DateRange): double
    - twoDaysRange(range: DateRange): DateRange
}

class IntermediateCancellation extends CancellationPolicy{
    + getCancellationFee(range: DateRange): double
}

class NoCancellation extends CancellationPolicy{
    + getCancellationFee(range: DateRange): double
}

class PriceCalculatorImpl implements PriceCalculatorInterface{

    + getPrice(range: DateRange): double
}

PriceCalculatorImpl -->"*" PriceForRange:priceForRanges

class CapacityFilter implements SearchFilter{
    - capacity: int

    + filter(housingList: List<Housing>): List<Housing>
}

class CityFilter implements SearchFilter{

    + filter(housingList: List<Housing>): List<Housing>
}

CityFilter -->"1" City : city

class DateRangeFilter implements SearchFilter{

    + filter(housingList: List<Housing>): List<Housing>
}

DateRangeFilter -->"1" DateRange:dateRange

class HousingSearch implements SearchFilter{

    + filter(housingList: List<Housing>): List<Housing>
}

HousingSearch -->"*" SearchFilter:filterList


class MinPriceFilter implements SearchFilter{
    - minPrice: double
    
    + filter(housingList: List<Housing>): List<Housing>
}

MinPriceFilter -->"1" DateRange:dateRange

class MaxPriceFilter implements SearchFilter{
    - maxPrice: double
    
    + filter(housingList: List<Housing>): List<Housing>
}

MaxPriceFilter -->"1" DateRange:dateRange

class HousingSearchBuilder {

    + HousingSearchBuilder(city: City, dateRange: DateRange)
    + setCapacity(capacity: int): HousingSearchBuilder
    + setMinPrice(minPrice: double): HousingSearchBuilder
    + setMaxPrice(maxPrice: double): HousingSearchBuilder
    + build(): SearchFilter
}

HousingSearchBuilder -->"*" HousingSearchBuilder:filterList
HousingSearchBuilder -->"1" DateRange: dateRange

class CategoryAverageView {
    - average: double

    + CategoryAverageView(average: double, category: Category)
    + getAverage(): double
    + getCategory(): Category
}

CategoryAverageView -->"1" Category: category

class CommentView {
    - text: String
    - commentedOn: LocalDate

    + CommentView(text: String, commentedOn: LocalDate, by: Ranker, scores: List<CategoryScore>)
    + fromRanking(ranking: Ranking): CommentView
    + getText(): String
    + getCommentedOn(): LocalDate
    + getBy(): Ranker
    + getScores(): List<CategoryScore>
}

CommentView -->"1" Ranker: by
CommentView -->"*" CategoryScore:scores

class HousingView {

    + HousingView(housing: Housing)
    + comments(): List<CommentView>
    + categoryAverages(): List<CategoryAverageView>
    + ownerDetails(): OwnerView
}

HousingView -->"1" Housing: housing

class OwnerRentalView {

    + OwnerRentalView(owner: Owner, currentHousing: Housing)
    + getTotalRentsForHousing(): long
    + getTotalRentsForAllHousings(): int
    + getTotalTimesHasRentedCurrentHousing(): long
    + getRentalsForCurrentHousing(): List<Housing>
}

OwnerRentalView -->"1" Owner: owner
OwnerRentalView -->"1" Housing: housing


class OwnerView {

    + OwnerView(owner: Owner, currentHousing: Housing)
    + getAllScores(): List<Integer>
    + getAverageScore(): double
    + getCreatedOn(): LocalDateTime
    + getOwnerRentalView(): OwnerRentalView
}

OwnerView -->"1" Owner: owner
OwnerView -->"1" Housing: currentHousing



interface SearchFilter {
	+filter(housingList: List<Housing> ): List<Housing> 
}

interface Categories{
	+  add(category:Category) : void
}

interface HousingTypes{
	+ add(housingType : HousingType) : void
}

interface Services{
	+  add(service:Service):void
	+  getAll():List<Service>
}

interface BookingAcceptedObserver{
	+ notifyBookingAccepted( booking:Booking) : void
}

interface BookingAcceptanceStrategy{
	+  isAcceptable(booking:Booking):boolean
}

interface BookingCancelledObserver{
	+  notifyBookingCancelled(booking:Booking):void
}

interface BookingStrategy {
	+ process(booking:Booking):void
}

interface EmailSender {
	+  sendEmail(to:String, body:String):void
}

interface EventPublisher {
	+ subscribeToPriceDrop(subscriber:PriceDropSubscriber):void
    + unsubscribeFromPriceDrop(subscriber:PriceDropSubscriber):void
    + subscribeToReservationCancelled(subscriber:ReservationCancelledSubscriber):void
    + unsubscribeFromReservationCancelled(subscriber:ReservationCancelledSubscriber):void
}

interface PaymentMethod{
	+applyCharge(amount:double):void
	+ receivePayment(amount:double):void
}

interface PriceCalculatorInterface {
	+ getPrice(range:DateRange):double
}

interface PriceDropSubscriber {
	+ onPriceDrop(message:String):void
}

interface Rankeable {
	+ addRanking(ranking:Ranking):void
	+ getRankings():List<Ranking>
}

interface Ranker {
	+ rank(ranking:Ranking):void
}

interface ReservationAcceptedSubscriber {
	+ onReservationAccepted(booking:Booking):void
}

interface ReservationCancelledSubscriber {
    + onReservationCancelled(message:String):void
}

interface Service {
	+ getName():String
}

interface BookingAcceptanceObservable {
    + addObserver(observer: BookingAcceptedObserver ): void
	+ removeObserver(observer: BookingAcceptedObserver ): void
}

@enduml
